services:
  playground:
#    image: codiew/codenire-playground:latest
    build:
      context: .
      dockerfile: Dockerfile
    profiles:
      - build
    ports:
      - "8081:8081/tcp"
    stdin_open: true
    tty: true
    restart: on-failure
    networks:
      - "sandnet"
    entrypoint: [
      "/playground",
      "--backend-url", "http://sandbox_dev/run",
      "--port", "8081",
    ]

  sandbox:
    container_name: sandbox_dev
    build:
      context: ./sandbox
      dockerfile: Dockerfile
    profiles:
      - build
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./example/dockerfiles:/dockerfiles
    networks:
      - sandnet
    stdin_open: true
    tty: true
    restart: "no"

    entrypoint: [
      "/usr/local/bin/sandbox",
      "--dockerFilesPath", "/dockerfiles",
      "--replicaContainerCnt", "1",
      "--port", ":80",
    ]

networks:
  sandnet:
    name: codenire