services:
#  plugins:
#    build:
#      context: .
#      dockerfile: Dockerfile.plugins
#    volumes:
#      - ./example/hooks/file:/plugins

  playground:
    container_name: play_dev
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GO_VERSION: "go1.23.4"
    volumes:
      - ./example/hooks/file:/hooks
    ports:
      - "8081:8081/tcp"
    stdin_open: true
    tty: true
    restart: "no"
    networks:
      - sandnet
    entrypoint: [
      "/app/codenire",
      "--backend-url", "http://sandbox_dev/run",
      "--port", "8081",
      "--hooks-dir", "/hooks"
    ]

  sandbox:
    container_name: sandbox_dev
    build:
      context: ./sandbox
      dockerfile: Dockerfile
    ports:
      - "8080:80/tcp"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./sandbox/provision:/provision
    networks:
      - sandnet
    stdin_open: true
    tty: true
    restart: "no"

    entrypoint: ["/usr/local/bin/play-sandbox"]


networks:
  sandnet:
    name: codenire