services:
  playground:
    image: codiew/codenire-playground:latest
    ports:
      - "8081:8081"
    stdin_open: true
    tty: true
    restart: always
    networks:
      - "sandnet"
    entrypoint: [
      "/playground",
      "--backend-url", "http://sandbox_dev/run",
      "--port", "8081",
    ]

  sandbox:
    container_name: sandbox_dev
    image: codiew/codenire-sandbox:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./dockerfiles:/dockerfiles
    networks:
      - sandnet
    stdin_open: true
    tty: true
    restart: always

    entrypoint: [
      "/usr/local/bin/sandbox",
      "--dockerFilesPath", "/dockerfiles",
      "--replicaContainerCnt", "1",
      "--port", "80",
    ]

networks:
  sandnet:
    name: codenire