openapi: 3.0.0
info:
  title: Submission API
  version: "1.0.0"
  description: API for managing code submissions

paths:
  /run:
    post:
      summary: Run Submission
      operationId: runSubmission
      requestBody:
        description: Run a submission
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SubmissionRequest'
      responses:
        "200":
          description: Submission ran successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SubmissionResponse'

components:
  schemas:
    SubmissionRequest:
      type: object
      properties:
        TemplateId:
          type: string
        Args:
          type: string
        Files:
          type: object
          additionalProperties:
            type: string
      required:
        - TemplateId
        - Args
        - Files
    SubmissionResponse:
      type: object
      properties:
        Events:
          type: array
          items:
            $ref: '#/components/schemas/SubmissionResponseEvents'
        Time:
          type: string
        Errors:
          type: array
          items:
            type: string
        Meta:
          type: object
          properties:
            Version:
              type: string
          additionalProperties: true
      required:
        - Events

    SubmissionResponseEvents:
      type: object
      properties:
        Message:
          type: string
        Kind:
          type: string
      required:
        - Message
        - Kind