openapi: 3.0.0
info:
  title: Submission API
  version: "1.0.0"
  description: API for managing code submissions

paths:
  /run:
    post:
      summary: Run Sandbox
      operationId: runSandbox
      requestBody:
        description: Run a sandbox
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SandboxRequest'
      responses:
        "200":
          description: Submission ran successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SandboxResponse'
  /templates/list:
    get:
      summary: Get image config list
      operationId: getImageConfigList
      responses:
        "200":
          description: Get list templates
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ImageConfigList'

components:
  schemas:
    SandboxResponse:
      type: object
      properties:
        error:
          type: string
        exitCode:
          type: integer
        stdout:
          type: string
          format: byte
        stderr:
          type: string
          format: byte
      required:
        - exitCode
        - stdout
        - stderr

    SandboxRequest:
      type: object
      properties:
        sandId:
          type: string
        binary:
          type: string
          description: files in tar archive encoded with base64
        args:
          type: string
        extendedOptions:
          type: object
          additionalProperties:
            type: string
        stdin:
          description: data which will available via stdin reader
          type: string
        action:
          type: string
      required:
        - sandId
        - binary
        - args
        - stdin
        - action

    ContainerOptions:
      type: object
      properties:
        CompileTTL:
          type: integer
        RunTTL:
          type: integer
        MemoryLimit:
          type: integer
      required:
        - SourceFile

    ImageConfigScriptOptions:
      type: object
      properties:
        SourceFile:
          type: string
      required:
        - SourceFile

    ImageTemplateConfig:
      type: object
      properties:
        Template:
          type: string
        Groups:
          type: array
          items:
            type: string
        Version:
          type: string
        ContainerOptions:
          $ref: '#/components/schemas/ContainerOptions'
        Workdir:
          type: string
        # Configuration provider (built-in, api, external)
        Provider:
          type: string
      required:
        - Template
        - Groups
        - ContainerOptions
        - Version
        - Workdir
        - Provider

    ImageActionConfig:
      type: object
      properties:
        IsDefault:
          type: boolean
          default: false
        Id:
          type: string
        Name:
          type: string
        CompileCmd:
          type: string
        RunCmd:
          type: string
        ScriptOptions:
          $ref: '#/components/schemas/ImageConfigScriptOptions'
        DefaultFiles:
          type: object
          additionalProperties:
            type: string
      required:
        - Id
        - Name
        - CompileCmd
        - RunCmd
        - ScriptOptions
        - DefaultFiles
        - IsDefault

    ImageConfig:
      type: object
      allOf:
        - type: object
          properties:
            Actions:
              type: object
              additionalProperties:
                $ref: '#/components/schemas/ImageActionConfig'
          required:
            - Actions
        - $ref: '#/components/schemas/ImageTemplateConfig'

    ImageConfigList:
      type: array
      items:
        $ref: '#/components/schemas/ImageConfig'