name: Check Open API Contracts

on:
  push:
    paths-ignore:
      - '**'

jobs:
  playground-build-and-push:
    runs-on: ubuntu-latest
    env:
      IMAGE_USERNAME: codiew
      IMAGE_NAME: codenire-playground
    steps:
      # Проверка кода из репозитория
      - name: Checkout repository
        uses: actions/checkout@v3
