# Build frontend app in /frontend/public path and force push it
# After force push run digital ocean rebuild static

on:
  push:
    paths:
      - 'sandbox/**'
    branches:
      - main
  pull_request:
    paths:
      - 'sandbox/**'
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: codenire-sandbox
    steps:
      # Проверка кода из репозитория
      - name: Checkout repository
        uses: actions/checkout@v3

      # Логин в Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Сборка Docker-образа
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME } }:latest .

      # Публикация Docker-образа
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/my-app:latest