# Build frontend app in /frontend/public path and force push it
# After force push run digital ocean rebuild static

on:
  push:
    paths:
      - 'sandbox/**'
      - '.github/workflows/sandbox-registry.yaml'
    branches:
      - main
  pull_request:
    paths:
      - 'sandbox/**'
      - '.github/workflows/sandbox-registry.yaml'
    branches:
      - main

jobs:
  sandbox-build-and-push:
    runs-on: ubuntu-latest
    env:
      IMAGE_USERNAME: codiew
      IMAGE_NAME: codiew/codenire-sandbox
      IMAGE_NAME_GVISOR: codiew/codenire-sandbox-gvisor
    steps:
      # Проверка кода из репозитория
      - name: Checkout repository
        uses: actions/checkout@v3

      # Логин в Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.IMAGE_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Сборка Docker-образа
      - name: Build Docker image
        working-directory: sandbox
        run: |
          docker build -f Dockerfile --tag=${{ env.IMAGE_NAME }} ..
          docker tag ${{ env.IMAGE_NAME }} ${{ env.IMAGE_NAME }}:latest
          docker build -f Dockerfile.gvisor --tag=${{ env.IMAGE_NAME_GVISOR }} ..
          docker tag ${{ env.IMAGE_NAME_GVISOR }} ${{ env.IMAGE_NAME_GVISOR }}:latest

      # Публикация Docker-образа
      - name: Push Docker image
        working-directory: sandbox
        run: |
          docker push ${{ env.IMAGE_NAME }}:latest
          docker push ${{ env.IMAGE_NAME_GVISOR }}:latest